Algoritmo "para-a"
// Disciplina   : [Lógica de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.! (função)
// Autor(a)    : Ana Beatriz
// Data atual  : 09/05/2022
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contadora de 15 ate 200 passo 1 faca
escreval(contadora^2)
fimpara
Fimalgoritmo